repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: check-yaml
      - id: end-of-file-fixer
      - id: trailing-whitespace
  - repo: https://github.com/charliermarsh/ruff-pre-commit
    rev: 'v0.4.8'
    hooks:
      - id: ruff
        args: [ "--fix" ]
  - repo: https://github.com/psf/black
    rev: 24.4.2  # Use the latest stable version or specify a version
    hooks:
      - id: black
