from sqlalchemy import Column, Integer, String

from src.main.database import Base as Base


class CustomerPromotionReactSummaryEntity(Base):
    __tablename__ = "cus_promotion_react_summary"

    cus_promotion_react_summary_seq = Column(Integer, primary_key=True, nullable=False)
    cus_cd = Column(String, nullable=False)
    campaign_strategy_id = Column(String, nullable=True)
    campaign_strategy_name = Column(String, nullable=True)
    strategy_theme_id = Column(String, nullable=True)
    strategy_theme_name = Column(String, nullable=True)
    audience_id = Column(String, nullable=False)
    audience_name = Column(String, nullable=False)
    coupon_no = Column(String, nullable=True)
    coupon_name = Column(String, nullable=True)
    send_cnt_before_3_years = Column(Integer)
    send_cnt_before_2_years = Column(Integer)
    send_cnt_before_1_year = Column(Integer)
    send_cnt_current_year = Column(Integer)
    send_cnt_2y = Column(Integer)
    send_cnt_1y = Column(Integer)
    send_cnt_6m = Column(Integer)
    send_cnt_3m = Column(Integer)
    send_cnt_1m = Column(Integer)
    send_cnt_ss = Column(Integer)
    send_cnt_fw = Column(Integer)
    recommend_cnt_before_3_years = Column(Integer)
    recommend_cnt_before_2_years = Column(Integer)
    recommend_cnt_before_1_year = Column(Integer)
    recommend_cnt_current_year = Column(Integer)
    recommend_cnt_2y = Column(Integer)
    recommend_cnt_1y = Column(Integer)
    recommend_cnt_6m = Column(Integer)
    recommend_cnt_3m = Column(Integer)
    recommend_cnt_1m = Column(Integer)
    recommend_cnt_ss = Column(Integer)
    recommend_cnt_fw = Column(Integer)
    response_cnt_before_3_years = Column(Integer)
    response_cnt_before_2_years = Column(Integer)
    response_cnt_before_1_year = Column(Integer)
    response_cnt_current_year = Column(Integer)
    response_cnt_2y = Column(Integer)
    response_cnt_1y = Column(Integer)
    response_cnt_6m = Column(Integer)
    response_cnt_3m = Column(Integer)
    response_cnt_1m = Column(Integer)
    response_cnt_ss = Column(Integer)
    response_cnt_fw = Column(Integer)
    use_offer_cnt_before_3_years = Column(Integer)
    use_offer_cnt_before_2_years = Column(Integer)
    use_offer_cnt_before_1_year = Column(Integer)
    use_offer_cnt_current_year = Column(Integer)
    use_offer_cnt_2y = Column(Integer)
    use_offer_cnt_1y = Column(Integer)
    use_offer_cnt_6m = Column(Integer)
    use_offer_cnt_3m = Column(Integer)
    use_offer_cnt_1m = Column(Integer)
    use_offer_cnt_ss = Column(Integer)
    use_offer_cnt_fw = Column(Integer)
    recommend_purchase_cnt_before_3_years = Column(Integer)
    recommend_purchase_cnt_before_2_years = Column(Integer)
    recommend_purchase_cnt_before_1_year = Column(Integer)
    recommend_purchase_cnt_current_year = Column(Integer)
    recommend_purchase_cnt_2y = Column(Integer)
    recommend_purchase_cnt_1y = Column(Integer)
    recommend_purchase_cnt_6m = Column(Integer)
    recommend_purchase_cnt_3m = Column(Integer)
    recommend_purchase_cnt_1m = Column(Integer)
    recommend_purchase_cnt_ss = Column(Integer)
    recommend_purchase_cnt_fw = Column(Integer)
