"""insert variable options data for target audience

Revision ID: a5ca1ee840ec
Revises: 21a121512d5a
Create Date: 2024-11-27 10:02:11.661458
Description: 타겟 오디언스 필터 생성에 필요한 데이터 초기화 작업
Target Table:
    - audience_predefined_variables
    - variable_options
    - variable_table_info

"""

from typing import Sequence, Union

from alembic import op
from sqlalchemy import text

# revision identifiers, used by Alembic.
revision: str = "a5ca1ee840ec"
down_revision: Union[str, None] = "349ffebc5779"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade():
    connection = op.get_bind()
    predefined_variable_insert_query = """
        INSERT INTO aivelabs_sv.audience_predefiend_variables
            (predef_var_seq, variable_id, variable_name, variable_group_code, variable_group_name, combination_type, input_cell_type, additional_variable, access_level, created_at, created_by, updated_at, updated_by)
        VALUES
            (101, 'cus_cd', '고객번호', 'customer_info', '고객정보', 'combi1', 'code_input', '{}', 30, NOW(), 'aivelabs', NOW(), 'aivelabs'),
            (102, 'sex_nm', '성별', 'customer_info', '고객정보', 'combi1', NULL, '{}', 30, NOW(), 'aivelabs', NOW(), 'aivelabs'),
            (103, 'this_year_birthday', '당해년도 생일', 'customer_info', '고객정보', 'combi1', 'datepicker', '{}', 30, NOW(), 'aivelabs', NOW(), 'aivelabs'),
            (104, 'this_year_wedding_anniversary', '결혼 기념일', 'customer_info', '고객정보', 'combi1', 'datepicker', '{}', 30, NOW(), 'aivelabs', NOW(), 'aivelabs'),
            (105, 'age', '연령', 'customer_info', '고객정보', 'combi1', 'number_input', '{}', 30, NOW(), 'aivelabs', NOW(), 'aivelabs'),
            (106, 'age_group_5', '연령대5대', 'customer_info', '고객정보', 'combi1', NULL, '{}', 30, NOW(), 'aivelabs', NOW(), 'aivelabs'),
            (107, 'created_date', '가입일', 'customer_info', '고객정보', 'combi1', 'datepicker', '{}', 30, NOW(), 'aivelabs', NOW(), 'aivelabs'),
            (108, 'group_name', '등급명', 'customer_status', '고객상태', 'combi1', NULL, '{}', 30, NOW(), 'aivelabs', NOW(), 'aivelabs'),
            (109, 'last_login_date', '마지막 접속일자', 'customer_status', '고객상태', 'combi1', 'datepicker', '{}', 30, NOW(), 'aivelabs', NOW(), 'aivelabs'),
            (110, 'last_purchase_date', '마지막 구매일자', 'customer_status', '고객상태', 'combi1', 'datepicker', '{}', 30, NOW(), 'aivelabs', NOW(), 'aivelabs'),
            (111, 'last_purchase_months_ago', '마지막구매 경과월', 'customer_status', '고객상태', 'combi1', NULL, '{}', 30, NOW(), 'aivelabs', NOW(), 'aivelabs'),
            (112, 'first_purchase_date', '첫 구매일자', 'customer_status', '고객상태', 'combi1', 'datepicker', '{}', 30, NOW(), 'aivelabs', NOW(), 'aivelabs'),
            (113, 'sms', 'SMS 수신여부', 'customer_status', '고객상태', 'combi1', NULL, '{}', 30, NOW(), 'aivelabs', NOW(), 'aivelabs'),
            (114, 'news_mail', '뉴스메일 수신여부', 'customer_status', '고객상태', 'combi1', NULL, '{}', 30, NOW(), 'aivelabs', NOW(), 'aivelabs'),
            (115, 'member_authentification', '회원인증 여부', 'customer_status', '고객상태', 'combi1', NULL, '{}', 30, NOW(), 'aivelabs', NOW(), 'aivelabs'),
            (116, 'available_points', '가용 예치금', 'customer_status', '고객상태', 'combi1', 'amount_input', '{}', 30, NOW(), 'aivelabs', NOW(), 'aivelabs'),
            (117, 'used_points', '사용 포인트', 'customer_status', '고객상태', 'combi1', 'amount_input', '{}', 30, NOW(), 'aivelabs', NOW(), 'aivelabs'),
            (118, 'total_points', '전체 포인트', 'customer_status', '고객상태', 'combi1', 'amount_input', '{}', 30, NOW(), 'aivelabs', NOW(), 'aivelabs'),
            (119, 'sale_amt_year', '올해구매금액', 'customer_status', '고객상태', 'combi1', 'amount_input', '{}', 30, NOW(), 'aivelabs', NOW(), 'aivelabs'),
            (120, 'cv_model', 'CV 고객단계', 'customer_status', '고객상태', 'combi1', NULL, '{}', 30, NOW(), 'aivelabs', NOW(), 'aivelabs'),
            (121, 'r_score_3m', 'recency 점수(3개월)', 'customer_status', '고객상태', 'combi1', 'number_input', '{}', 30, NOW(), 'aivelabs', NOW(), 'aivelabs'),
            (122, 'f_score_3m', 'frequency 점수(3개월)', 'customer_status', '고객상태', 'combi1', 'number_input', '{}', 30, NOW(), 'aivelabs', NOW(), 'aivelabs'),
            (123, 'm_score_3m', 'monetary 점수(3개월)', 'customer_status', '고객상태', 'combi1', 'number_input', '{}', 30, NOW(), 'aivelabs', NOW(), 'aivelabs'),
            (124, 'rfm_score_3m', 'rfm 점수(3개월)', 'customer_status', '고객상태', 'combi1', 'number_input', '{}', 30, NOW(), 'aivelabs', NOW(), 'aivelabs'),
            (125, 'r_score_6m', 'recency 점수(6개월)', 'customer_status', '고객상태', 'combi1', 'number_input', '{}', 30, NOW(), 'aivelabs', NOW(), 'aivelabs'),
            (126, 'f_score_6m', 'frequency 점수(6개월)', 'customer_status', '고객상태', 'combi1', 'number_input', '{}', 30, NOW(), 'aivelabs', NOW(), 'aivelabs'),
            (127, 'm_score_6m', 'monetary 점수(6개월)', 'customer_status', '고객상태', 'combi1', 'number_input', '{}', 30, NOW(), 'aivelabs', NOW(), 'aivelabs'),
            (128, 'rfm_score_6m', 'rfm 점수(6개월)', 'customer_status', '고객상태', 'combi1', 'number_input', '{}', 30, NOW(), 'aivelabs', NOW(), 'aivelabs'),
            (129, 'r_score_9m', 'recency 점수(9개월)', 'customer_status', '고객상태', 'combi1', 'number_input', '{}', 30, NOW(), 'aivelabs', NOW(), 'aivelabs'),
            (130, 'f_score_9m', 'frequency 점수(9개월)', 'customer_status', '고객상태', 'combi1', 'number_input', '{}', 30, NOW(), 'aivelabs', NOW(), 'aivelabs'),
            (131, 'm_score_9m', 'monetary 점수(9개월)', 'customer_status', '고객상태', 'combi1', 'number_input', '{}', 30, NOW(), 'aivelabs', NOW(), 'aivelabs'),
            (132, 'rfm_score_9m', 'rfm 점수(9개월)', 'customer_status', '고객상태', 'combi1', 'number_input', '{}', 30, NOW(), 'aivelabs', NOW(), 'aivelabs'),
            (133, 'r_score_1y', 'recency 점수(1년)', 'customer_status', '고객상태', 'combi1', 'number_input', '{}', 30, NOW(), 'aivelabs', NOW(), 'aivelabs'),
            (134, 'f_score_1y', 'frequency 점수(1년)', 'customer_status', '고객상태', 'combi1', 'number_input', '{}', 30, NOW(), 'aivelabs', NOW(), 'aivelabs'),
            (135, 'm_score_1y', 'monetary 점수(1년)', 'customer_status', '고객상태', 'combi1', 'number_input', '{}', 30, NOW(), 'aivelabs', NOW(), 'aivelabs'),
            (136, 'rfm_score_1y', 'rfm 점수', 'customer_status', '고객상태', 'combi1', 'number_input', '{}', 30, NOW(), 'aivelabs', NOW(), 'aivelabs'),
            (137, 'sale_qty', '구매수량', 'purchase', '구매', 'combi1', 'number_input', '{it_gb_nm,item_nm,product_name,option_value_1,option_value_2}', 30, NOW(), 'aivelabs', NOW(), 'aivelabs'),
            (138, 'sale_amt', '구매금액', 'purchase', '구매', 'combi1', 'amount_input', '{it_gb_nm,item_nm,product_name,option_value_1,option_value_2}', 30, NOW(), 'aivelabs', NOW(), 'aivelabs'),
            (140, 'age_group_10', '연령대10대', 'customer_info', '고객정보', 'combi1', NULL, '{}', 30, NOW(), 'aivelabs', NOW(), 'aivelabs'),
            (141, 'coupon_expired', '쿠폰만료 7일 이내', 'customer_status', '고객상태', 'combi1', NULL, '{}', 30, NOW(), 'aivelabs', NOW(), 'aivelabs'),
            (142, 'is_cart', '장바구니 업데이트 1일 이내', 'customer_status', '고객상태', 'combi1', null, '{}', 30, NOW(), 'aivelabs', NOW(), 'aivelabs'),
            (144, 'is_wishlist', '위시리스트 업데이트 1일 이내', 'customer_status', '고객상태', 'combi1', null, '{}', 30, NOW(), 'aivelabs', NOW(), 'aivelabs'),
            (146, 'near_promotion_amount', '회원 등급 상승까지 잔여 구매금액 10% 이내 고객', 'customer_status', '고객상태', 'combi1', null, '{}', 30, NOW(), 'aivelabs', NOW(), 'aivelabs'),
            (147, 'near_promotion_cnt', '회원 등급 상승까지 한 건의 구매가 남은 고객', 'customer_status', '고객상태', 'combi1', null, '{}', 30, NOW(), 'aivelabs', NOW(), 'aivelabs'),
            (148, 'promoted_customer', '최근 2일 이내에 회원 등급이 상승한 고객', 'customer_status', '고객상태', 'combi1', null, '{}', 30, NOW(), 'aivelabs', NOW(), 'aivelabs'),
            (149, 'purchase_cnt', '구매횟수(최근 1년)', 'customer_status', '고객상태', 'combi1', 'number_input', '{}', 30, NOW(), 'aivelabs', NOW(), 'aivelabs'),
            (150, 'first_purchase', '어제 첫 구매가 발생한 고객', 'customer_status', '고객상태', 'combi1', null, '{}', 30, NOW(), 'aivelabs', NOW(), 'aivelabs'),
            (151, 'birthday_7_left', '생일까지 7일 남은 고객', 'customer_status', '고객상태', 'combi1', null, '{}', 30, NOW(), 'aivelabs', NOW(), 'aivelabs'),
            (152, 'visit_count', '방문일수', 'customer_action', '고객행동', 'combi1', 'number_input', '{visit_option_product_name,visit_option_full_category_name_1,visit_option_full_category_name_2}', 30, NOW(), 'aivelabs', NOW(), 'aivelabs'),
            (153, 'visit_count_category', '방문일수(최근)', 'customer_action', '고객행동', 'combi1', 'number_input', '{visit_option_product_name,visit_option_full_category_name_1,visit_option_full_category_name_2}', 30, NOW(), 'aivelabs', NOW(), 'aivelabs'),
            (156, 'visit_option_product_name', '방문 상품', 'item', '카테고리', 'combi1', null, '{}', 30, NOW(), 'aivelabs', NOW(), 'aivelabs'),
            (157, 'visit_option_full_category_name_1', '방문 카테고리(대)', 'item', '카테고리', 'combi1', null, '{}', 30, NOW(), 'aivelabs', NOW(), 'aivelabs'),
            (158, 'visit_option_full_category_name_2', '방문 카테고리(중)', 'item', '카테고리', 'combi1', null, '{}', 30, NOW(), 'aivelabs', NOW(), 'aivelabs'),
            (159, 'visit_option_full_category_name_3', '방문 카테고리(소)', 'item', '카테고리', 'combi1', null, '{}', 30, NOW(), 'aivelabs', NOW(), 'aivelabs'),
            (160, 'visit_product_name', '관심 상품', 'customer_action', '고객행동', 'combi1', null, '{}', 30, NOW(), 'aivelabs', NOW(), 'aivelabs'),
            (161, 'visit_full_category_name_1', '관심 카테고리(대)', 'customer_action', '고객행동', 'combi1', null, '{}', 30, NOW(), 'aivelabs', NOW(), 'aivelabs'),
            (162, 'visit_full_category_name_2', '관심 카테고리(중)', 'customer_action', '고객행동', 'combi1', null, '{}', 30, NOW(), 'aivelabs', NOW(), 'aivelabs'),
            (163, 'visit_full_category_name_3', '관심 카테고리(소)', 'customer_action', '고객행동', 'combi1', null, '{}', 30, NOW(), 'aivelabs', NOW(), 'aivelabs'),
            (164, 'visit_page_title', '방문 페이지', 'customer_action', '고객행동', 'combi1', null, '{}', 30, NOW(), 'aivelabs', NOW(), 'aivelabs'),
            (165, 'it_gb_nm', '카테고리', 'item', '상품', 'combi1', null, '{}', 30, NOW(), 'aivelabs', NOW(), 'aivelabs'),
            (166, 'item_nm', '세부 카테고리', 'item', '상품', 'combi1', null, '{}', 30, NOW(), 'aivelabs', NOW(), 'aivelabs'),
            (167, 'option_value_1', '세부옵션 선택1', 'item', '상품', 'combi1', null, '{}', 30, NOW(), 'aivelabs', NOW(), 'aivelabs'),
            (168, 'option_value_2', '세부옵션 선택2', 'item', '상품', 'combi1', null, '{}', 30, NOW(), 'aivelabs', NOW(), 'aivelabs'),
            (169, 'kakao_friends_yn', '카카오플러스 친구 여부', 'kakao_friends_yn', '카카오플러스 친구', 'combi1', null, '{}', 30, NOW(), 'aivelabs', NOW(), 'aivelabs'),
            (170, 'product_name', '상품명', 'item', '상품', 'combi1', null, '{}', 30, NOW(), 'aivelabs', NOW(), 'aivelabs'),
            (171, 'is_first_best_items', '첫 구매 Best 상품 추천 여부', 'recsys_model', '상품추천', 'combi1', null, '{}', 30, NOW(), 'aivelabs', NOW(), 'aivelabs'),
            (172, 'is_steady_items', '스테디셀러 상품 추천 여부', 'recsys_model', '상품추천', 'combi1', null, '{}', 30, NOW(), 'aivelabs', NOW(), 'aivelabs'),
            (173, 'is_best_new_items', '신상품 추천 여부', 'recsys_model', '상품추천', 'combi1', null, '{}', 30, NOW(), 'aivelabs', NOW(), 'aivelabs'),
            (174, 'is_best_category_items', '선호 카테고리 Best 상품 추천 여부', 'recsys_model', '상품추천', 'combi1', null, '{}', 30, NOW(), 'aivelabs', NOW(), 'aivelabs'),
            (175, 'is_best_promo_items', '최대 할인 상품 추천 여부', 'recsys_model', '상품추천', 'combi1', null, '{}', 30, NOW(), 'aivelabs', NOW(), 'aivelabs'),
            (176, 'is_best_cross_items', 'Next 구매 확률 높은 상품 추천 여부', 'recsys_model', '상품추천', 'combi1', null, '{}', 30, NOW(), 'aivelabs', NOW(), 'aivelabs');
    """
    connection.execute(text(predefined_variable_insert_query))

    variable_options_insert_query = """
        INSERT INTO aivelabs_sv.variable_options (
        predef_var_seq, variable_id, combination_type, data_type, data_type_desc,
        option_id, option_name, cell_type, input_cell_type, querying_type,
        created_at, created_by, updated_at, updated_by, additional_only,
        option_order_cols, component_order_cols
        )
        VALUES
            (101, 'cus_cd', '101', 'd_in', '포함 조건', 'in', '포함', 'single_select', null, 'data', now(), 'aivelabs', now(), 'aivelabs', 'N', 1, 1),
            (101, 'cus_cd', '101', 'd_in', '포함 조건', 'notin', '미포함', 'single_select', null, 'data', now(), 'aivelabs', now(), 'aivelabs', 'N', 2, 1),
            (107, 'created_date', '107', 'd_cond', '조건 선택', 'gt', '이상', 'single_select', null, 'data', now(), 'aivelabs', now(), 'aivelabs', 'N', 1, 1),
            (107, 'created_date', '107', 'd_cond', '조건 선택', 'ls', '이하', 'single_select', null, 'data', now(), 'aivelabs', now(), 'aivelabs', 'N', 2, 1),
            (107, 'created_date', '107', 'd_cond', '조건 선택', 'eq', '같음', 'single_select', null, 'data', now(), 'aivelabs', now(), 'aivelabs', 'N', 3, 1),
            (109, 'last_login_date', '109', 'd_cond', '조건 선택', 'gt', '이상', 'single_select', null, 'data', now(), 'aivelabs', now(), 'aivelabs', 'N', 1, 1),
            (109, 'last_login_date', '109', 'd_cond', '조건 선택', 'eq', '같음', 'single_select', null, 'data', now(), 'aivelabs', now(), 'aivelabs', 'N', 3, 1),
            (109, 'last_login_date', '109', 'd_cond', '조건 선택', 'ls', '이하', 'single_select', null, 'data', now(), 'aivelabs', now(), 'aivelabs', 'N', 2, 1),
            (110, 'last_purchase_date', '34', 'd_cond', '조건 선택', 'eq', '같음', 'single_select', null, 'data', now(), 'aivelabs', now(), 'aivelabs', 'N', 3, 1),
            (110, 'last_purchase_date', '34', 'd_cond', '조건 선택', 'gt', '이상', 'single_select', null, 'data', now(), 'aivelabs', now(), 'aivelabs', 'N', 1, 1),
            (110, 'last_purchase_date', '34', 'd_cond', '조건 선택', 'ls', '이하', 'single_select', null, 'data', now(), 'aivelabs', now(), 'aivelabs', 'N', 2, 1),
            (111, 'last_purchase_months_ago', '156', 'd_month', '월 선택', '8', '8', 'single_select', null, 'data', now(), 'aivelabs', now(), 'aivelabs', 'N', 8, 2),
            (111, 'last_purchase_months_ago', '156', 'd_month', '월 선택', '9', '9', 'single_select', null, 'data', now(), 'aivelabs', now(), 'aivelabs', 'N', 9, 2),
            (111, 'last_purchase_months_ago', '156', 'd_month', '월 선택', '10', '10', 'single_select', null, 'data', now(), 'aivelabs', now(), 'aivelabs', 'N', 10, 2),
            (111, 'last_purchase_months_ago', '156', 'd_month', '월 선택', '11', '11', 'single_select', null, 'data', now(), 'aivelabs', now(), 'aivelabs', 'N', 11, 2),
            (111, 'last_purchase_months_ago', '156', 'd_month', '월 선택', '12', '12', 'single_select', null, 'data', now(), 'aivelabs', now(), 'aivelabs', 'N', 12, 2),
            (111, 'last_purchase_months_ago', '156', 'd_month', '월 선택', '13', '13', 'single_select', null, 'data', now(), 'aivelabs', now(), 'aivelabs', 'N', 13, 2),
            (111, 'last_purchase_months_ago', '156', 'd_month', '월 선택', '14', '14', 'single_select', null, 'data', now(), 'aivelabs', now(), 'aivelabs', 'N', 14, 2),
            (111, 'last_purchase_months_ago', '156', 'd_month', '월 선택', '15', '15', 'single_select', null, 'data', now(), 'aivelabs', now(), 'aivelabs', 'N', 15, 2),
            (111, 'last_purchase_months_ago', '156', 'd_month', '월 선택', '16', '16', 'single_select', null, 'data', now(), 'aivelabs', now(), 'aivelabs', 'N', 16, 2),
            (111, 'last_purchase_months_ago', '156', 'd_month', '월 선택', '17', '17', 'single_select', null, 'data', now(), 'aivelabs', now(), 'aivelabs', 'N', 17, 2),
            (111, 'last_purchase_months_ago', '156', 'd_month', '월 선택', '18', '18', 'single_select', null, 'data', now(), 'aivelabs', now(), 'aivelabs', 'N', 18, 2),
            (111, 'last_purchase_months_ago', '156', 'd_month', '월 선택', '19', '19', 'single_select', null, 'data', now(), 'aivelabs', now(), 'aivelabs', 'N', 19, 2),
            (111, 'last_purchase_months_ago', '156', 'd_month', '월 선택', '20', '20', 'single_select', null, 'data', now(), 'aivelabs', now(), 'aivelabs', 'N', 20, 2),
            (111, 'last_purchase_months_ago', '156', 'd_month', '월 선택', '21', '21', 'single_select', null, 'data', now(), 'aivelabs', now(), 'aivelabs', 'N', 21, 2),
            (111, 'last_purchase_months_ago', '156', 'd_month', '월 선택', '22', '22', 'single_select', null, 'data', now(), 'aivelabs', now(), 'aivelabs', 'N', 22, 2),
            (111, 'last_purchase_months_ago', '156', 'd_month', '월 선택', '23', '23', 'single_select', null, 'data', now(), 'aivelabs', now(), 'aivelabs', 'N', 23, 2),
            (111, 'last_purchase_months_ago', '156', 'd_month', '월 선택', '24', '24', 'single_select', null, 'data', now(), 'aivelabs', now(), 'aivelabs', 'N', 24, 2),
            (111, 'last_purchase_months_ago', '156', 'd_month', '월 선택', '25', '25', 'single_select', null, 'data', now(), 'aivelabs', now(), 'aivelabs', 'N', 25, 2),
            (111, 'last_purchase_months_ago', '156', 'd_month', '월 선택', '26', '26', 'single_select', null, 'data', now(), 'aivelabs', now(), 'aivelabs', 'N', 26, 2),
            (111, 'last_purchase_months_ago', '156', 'd_month', '월 선택', '27', '27', 'single_select', null, 'data', now(), 'aivelabs', now(), 'aivelabs', 'N', 27, 2),
            (111, 'last_purchase_months_ago', '156', 'd_month', '월 선택', '28', '28', 'single_select', null, 'data', now(), 'aivelabs', now(), 'aivelabs', 'N', 28, 2),
            (111, 'last_purchase_months_ago', '156', 'd_month', '월 선택', '29', '29', 'single_select', null, 'data', now(), 'aivelabs', now(), 'aivelabs', 'N', 29, 2),
            (111, 'last_purchase_months_ago', '156', 'd_month', '월 선택', '30', '30', 'single_select', null, 'data', now(), 'aivelabs', now(), 'aivelabs', 'N', 30, 2),
            (111, 'last_purchase_months_ago', '156', 'd_month', '월 선택', '31', '31', 'single_select', null, 'data', now(), 'aivelabs', now(), 'aivelabs', 'N', 31, 2),
            (111, 'last_purchase_months_ago', '156', 'd_month', '월 선택', '32', '32', 'single_select', null, 'data', now(), 'aivelabs', now(), 'aivelabs', 'N', 32, 2),
            (111, 'last_purchase_months_ago', '156', 'd_month', '월 선택', '33', '33', 'single_select', null, 'data', now(), 'aivelabs', now(), 'aivelabs', 'N', 33, 2),
            (111, 'last_purchase_months_ago', '156', 'd_month', '월 선택', '34', '34', 'single_select', null, 'data', now(), 'aivelabs', now(), 'aivelabs', 'N', 34, 2),
            (111, 'last_purchase_months_ago', '156', 'd_cond', '조건선택', 'gt', '이상', 'single_select', null, 'data', now(), 'aivelabs', now(), 'aivelabs', 'N', 1, 1),
            (111, 'last_purchase_months_ago', '156', 'd_cond', '조건선택', 'ls', '이하', 'single_select', null, 'data', now(), 'aivelabs', now(), 'aivelabs', 'N', 2, 1),
            (111, 'last_purchase_months_ago', '156', 'd_cond', '조건선택', 'eq', '같음', 'single_select', null, 'data', now(), 'aivelabs', now(), 'aivelabs', 'N', 3, 1),
            (111, 'last_purchase_months_ago', '156', 'd_month', '월 선택', '1', '1', 'single_select', null, 'data', now(), 'aivelabs', now(), 'aivelabs', 'N', 1, 2),
            (111, 'last_purchase_months_ago', '156', 'd_month', '월 선택', '2', '2', 'single_select', null, 'data', now(), 'aivelabs', now(), 'aivelabs', 'N', 2, 2),
            (111, 'last_purchase_months_ago', '156', 'd_month', '월 선택', '3', '3', 'single_select', null, 'data', now(), 'aivelabs', now(), 'aivelabs', 'N', 3, 2),
            (111, 'last_purchase_months_ago', '156', 'd_month', '월 선택', '4', '4', 'single_select', null, 'data', now(), 'aivelabs', now(), 'aivelabs', 'N', 4, 2),
            (111, 'last_purchase_months_ago', '156', 'd_month', '월 선택', '5', '5', 'single_select', null, 'data', now(), 'aivelabs', now(), 'aivelabs', 'N', 5, 2),
            (111, 'last_purchase_months_ago', '156', 'd_month', '월 선택', '6', '6', 'single_select', null, 'data', now(), 'aivelabs', now(), 'aivelabs', 'N', 6, 2),
            (111, 'last_purchase_months_ago', '156', 'd_month', '월 선택', '7', '7', 'single_select', null, 'data', now(), 'aivelabs', now(), 'aivelabs', 'N', 7, 2),
            (111, 'last_purchase_months_ago', '156', 'd_month', '월 선택', '35', '35', 'single_select', null, 'data', now(), 'aivelabs', now(), 'aivelabs', 'N', 35, 2),
            (111, 'last_purchase_months_ago', '156', 'd_month', '월 선택', '36', '36', 'single_select', null, 'data', now(), 'aivelabs', now(), 'aivelabs', 'N', 36, 2),
            (112, 'first_purchase_date', '112', 'd_cond', '조건 선택', 'ls', '이하', 'single_select', null, 'data', now(), 'aivelabs', now(), 'aivelabs', 'N', 2, 1),
            (112, 'first_purchase_date', '112', 'd_cond', '조건 선택', 'eq', '같음', 'single_select', null, 'data', now(), 'aivelabs', now(), 'aivelabs', 'N', 3, 1),
            (112, 'first_purchase_date', '112', 'd_cond', '조건 선택', 'gt', '이상', 'single_select', null, 'data', now(), 'aivelabs', now(), 'aivelabs', 'N', 1, 1),
            (113, 'sms', '113', 'd_tf', 'SMS 수신여부', 'F', 'N', 'single_select', null, 'data', now(), 'aivelabs', now(), 'aivelabs', 'N', 2, 1),
            (113, 'sms', '113', 'd_tf', 'SMS 수신여부', 'T', 'Y', 'single_select', null, 'data', now(), 'aivelabs', now(), 'aivelabs', 'N', 1, 1),
            (114, 'news_mail', '114', 'd_yn', '뉴스메일 수신여부', 'Y', 'Y', 'single_select', null, 'data', now(), 'aivelabs', now(), 'aivelabs', 'N', 1, 1),
            (114, 'news_mail', '114', 'd_yn', '뉴스메일 수신여부', 'N', 'N', 'single_select', null, 'data', now(), 'aivelabs', now(), 'aivelabs', 'N', 2, 1),
            (116, 'available_points', '116', 'd_cond', '조건 선택', 'gt', '이상', 'single_select', null, 'data', now(), 'aivelabs', now(), 'aivelabs', 'N', 1, 1),
            (116, 'available_points', '116', 'd_cond', '조건 선택', 'ls', '이하', 'single_select', null, 'data', now(), 'aivelabs', now(), 'aivelabs', 'N', 2, 1),
            (117, 'used_points', '117', 'd_cond', '조건 선택', 'ls', '이하', 'single_select', null, 'data', now(), 'aivelabs', now(), 'aivelabs', 'N', 2, 1),
            (117, 'used_points', '117', 'd_cond', '조건 선택', 'gt', '이상', 'single_select', null, 'data', now(), 'aivelabs', now(), 'aivelabs', 'N', 1, 1),
            (118, 'total_points', '118', 'd_cond', '조건 선택', 'gt', '이상', 'single_select', null, 'data', now(), 'aivelabs', now(), 'aivelabs', 'N', 1, 1),
            (118, 'total_points', '118', 'd_cond', '조건 선택', 'ls', '이하', 'single_select', null, 'data', now(), 'aivelabs', now(), 'aivelabs', 'N', 2, 1),
            (119, 'sale_amt_year', '119', 'd_cond', '조건 선택', 'gt', '이상', 'single_select', null, 'data', now(), 'aivelabs', now(), 'aivelabs', 'N', 1, 1),
            (119, 'sale_amt_year', '119', 'd_cond', '조건 선택', 'ls', '이하', 'single_select', null, 'data', now(), 'aivelabs', now(), 'aivelabs', 'N', 2, 1),
            (120, 'cv_model', '120', 'd_cv', 'CV 고객단계', 'ACTIVE_CUSTOMER4', 'ACTIVE_CUSTOMER4', 'multi_select', null, 'data', now(), 'aivelabs', now(), 'aivelabs', 'N', 9, 1),
            (120, 'cv_model', '120', 'd_cv', 'CV 고객단계', 'INACTIVE_NEW_M1', 'INACTIVE_NEW_M1', 'multi_select', null, 'data', now(), 'aivelabs', now(), 'aivelabs', 'N', 2, 1),
            (120, 'cv_model', '120', 'd_cv', 'CV 고객단계', 'INACTIVE_NEW_M3', 'INACTIVE_NEW_M3', 'multi_select', null, 'data', now(), 'aivelabs', now(), 'aivelabs', 'N', 3, 1),
            (120, 'cv_model', '120', 'd_cv', 'CV 고객단계', 'INACTIVE_NEW_M6', 'INACTIVE_NEW_M6', 'multi_select', null, 'data', now(), 'aivelabs', now(), 'aivelabs', 'N', 4, 1),
            (120, 'cv_model', '120', 'd_cv', 'CV 고객단계', 'INACTIVE_NEW_M9', 'INACTIVE_NEW_M9', 'multi_select', null, 'data', now(), 'aivelabs', now(), 'aivelabs', 'N', 5, 1),
            (120, 'cv_model', '120', 'd_cv', 'CV 고객단계', 'ACTIVE_CUSTOMER3', 'ACTIVE_CUSTOMER3', 'multi_select', null, 'data', now(), 'aivelabs', now(), 'aivelabs', 'N', 8, 1),
            (120, 'cv_model', '120', 'd_cv', 'CV 고객단계', 'ACTIVE_CUSTOMER2', 'ACTIVE_CUSTOMER2', 'multi_select', null, 'data', now(), 'aivelabs', now(), 'aivelabs', 'N', 7, 1),
            (120, 'cv_model', '120', 'd_cv', 'CV 고객단계', 'ACTIVE_CUSTOMER1', 'ACTIVE_CUSTOMER1', 'multi_select', null, 'data', now(), 'aivelabs', now(), 'aivelabs', 'N', 6, 1),
            (120, 'cv_model', '120', 'd_cv', 'CV 고객단계', 'NEW_CUSTOMER', 'NEW_CUSTOMER', 'multi_select', null, 'data', now(), 'aivelabs', now(), 'aivelabs', 'N', 1, 1),
            (120, 'cv_model', '120', 'd_cv', 'CV 고객단계', 'INACTIVE_ACT1_M3', 'INACTIVE_ACT1_M3', 'multi_select', null, 'data', now(), 'aivelabs', now(), 'aivelabs', 'N', 10, 1),
            (120, 'cv_model', '120', 'd_cv', 'CV 고객단계', 'INACTIVE_ACT1_M6', 'INACTIVE_ACT1_M6', 'multi_select', null, 'data', now(), 'aivelabs', now(), 'aivelabs', 'N', 11, 1),
            (120, 'cv_model', '120', 'd_cv', 'CV 고객단계', 'INACTIVE_ACT1_M9', 'INACTIVE_ACT1_M9', 'multi_select', null, 'data', now(), 'aivelabs', now(), 'aivelabs', 'N', 12, 1),
            (120, 'cv_model', '120', 'd_cv', 'CV 고객단계', 'INACTIVE_ACT2_M3', 'INACTIVE_ACT2_M3', 'multi_select', null, 'data', now(), 'aivelabs', now(), 'aivelabs', 'N', 13, 1),
            (120, 'cv_model', '120', 'd_cv', 'CV 고객단계', 'INACTIVE_ACT2_M6', 'INACTIVE_ACT2_M6', 'multi_select', null, 'data', now(), 'aivelabs', now(), 'aivelabs', 'N', 14, 1),
            (120, 'cv_model', '120', 'd_cv', 'CV 고객단계', 'INACTIVE_ACT2_M9', 'INACTIVE_ACT2_M9', 'multi_select', null, 'data', now(), 'aivelabs', now(), 'aivelabs', 'N', 15, 1),
            (120, 'cv_model', '120', 'd_cv', 'CV 고객단계', 'INACTIVE_ACT3_M3', 'INACTIVE_ACT3_M3', 'multi_select', null, 'data', now(), 'aivelabs', now(), 'aivelabs', 'N', 16, 1),
            (120, 'cv_model', '120', 'd_cv', 'CV 고객단계', 'INACTIVE_ACT3_M6', 'INACTIVE_ACT3_M6', 'multi_select', null, 'data', now(), 'aivelabs', now(), 'aivelabs', 'N', 17, 1),
            (120, 'cv_model', '120', 'd_cv', 'CV 고객단계', 'INACTIVE_ACT3_M9', 'INACTIVE_ACT3_M9', 'multi_select', null, 'data', now(), 'aivelabs', now(), 'aivelabs', 'N', 18, 1),
            (120, 'cv_model', '120', 'd_cv', 'CV 고객단계', 'INACTIVE_ACT4_M3', 'INACTIVE_ACT4_M3', 'multi_select', null, 'data', now(), 'aivelabs', now(), 'aivelabs', 'N', 19, 1),
            (120, 'cv_model', '120', 'd_cv', 'CV 고객단계', 'INACTIVE_ACT4_M6', 'INACTIVE_ACT4_M6', 'multi_select', null, 'data', now(), 'aivelabs', now(), 'aivelabs', 'N', 20, 1),
            (120, 'cv_model', '120', 'd_cv', 'CV 고객단계', 'INACTIVE_ACT4_M9', 'INACTIVE_ACT4_M9', 'multi_select', null, 'data', now(), 'aivelabs', now(), 'aivelabs', 'N', 21, 1),
            (120, 'cv_model', '120', 'd_cv', 'CV 고객단계', 'CHURN_M12', 'CHURN_M12', 'multi_select', null, 'data', now(), 'aivelabs', now(), 'aivelabs', 'N', 22, 1),
            (120, 'cv_model', '120', 'd_cv', 'CV 고객단계', 'CHURN_M18', 'CHURN_M18', 'multi_select', null, 'data', now(), 'aivelabs', now(), 'aivelabs', 'N', 23, 1),
            (120, 'cv_model', '120', 'd_cv', 'CV 고객단계', 'CHURN_M24', 'CHURN_M24', 'multi_select', null, 'data', now(), 'aivelabs', now(), 'aivelabs', 'N', 24, 1),
            (120, 'cv_model', '120', 'd_cv', 'CV 고객단계', 'CHURN_M30', 'CHURN_M30', 'multi_select', null, 'data', now(), 'aivelabs', now(), 'aivelabs', 'N', 25, 1),
            (121, 'r_score_3m', '121', 'd_cond', '조건 선택', 'gt', '이상', 'single_select', null, 'data', now(), 'aivelabs', now(), 'aivelabs', 'N', 1, 2),
            (121, 'r_score_3m', '121', 'd_cond', '조건 선택', 'ls', '이하', 'single_select', null, 'data', now(), 'aivelabs', now(), 'aivelabs', 'N', 2, 2),
            (122, 'f_score_3m', '122', 'd_cond', '조건 선택', 'ls', '이하', 'single_select', null, 'data', now(), 'aivelabs', now(), 'aivelabs', 'N', 2, 2),
            (122, 'f_score_3m', '122', 'd_cond', '조건 선택', 'gt', '이상', 'single_select', null, 'data', now(), 'aivelabs', now(), 'aivelabs', 'N', 1, 2),
            (123, 'm_score_3m', '123', 'd_cond', '조건 선택', 'gt', '이상', 'single_select', null, 'data', now(), 'aivelabs', now(), 'aivelabs', 'N', 1, 2),
            (123, 'm_score_3m', '123', 'd_cond', '조건 선택', 'ls', '이하', 'single_select', null, 'data', now(), 'aivelabs', now(), 'aivelabs', 'N', 2, 2),
            (124, 'rfm_score_3m', '124', 'd_cond', '조건 선택', 'ls', '이하', 'single_select', null, 'data', now(), 'aivelabs', now(), 'aivelabs', 'N', 2, 2),
            (124, 'rfm_score_3m', '124', 'd_cond', '조건 선택', 'gt', '이상', 'single_select', null, 'data', now(), 'aivelabs', now(), 'aivelabs', 'N', 1, 2),
            (125, 'r_score_6m', '125', 'd_cond', '조건 선택', 'gt', '이상', 'single_select', null, 'data', now(), 'aivelabs', now(), 'aivelabs', 'N', 1, 2),
            (125, 'r_score_6m', '125', 'd_cond', '조건 선택', 'ls', '이하', 'single_select', null, 'data', now(), 'aivelabs', now(), 'aivelabs', 'N', 2, 2),
            (126, 'f_score_6m', '126', 'd_cond', '조건 선택', 'gt', '이상', 'single_select', null, 'data', now(), 'aivelabs', now(), 'aivelabs', 'N', 1, 2),
            (126, 'f_score_6m', '126', 'd_cond', '조건 선택', 'ls', '이하', 'single_select', null, 'data', now(), 'aivelabs', now(), 'aivelabs', 'N', 2, 2),
            (127, 'm_score_6m', '127', 'd_cond', '조건 선택', 'ls', '이하', 'single_select', null, 'data', now(), 'aivelabs', now(), 'aivelabs', 'N', 2, 2),
            (127, 'm_score_6m', '127', 'd_cond', '조건 선택', 'gt', '이상', 'single_select', null, 'data', now(), 'aivelabs', now(), 'aivelabs', 'N', 1, 2),
            (128, 'rfm_score_6m', '128', 'd_cond', '조건 선택', 'gt', '이상', 'single_select', null, 'data', now(), 'aivelabs', now(), 'aivelabs', 'N', 1, 2),
            (128, 'rfm_score_6m', '128', 'd_cond', '조건 선택', 'ls', '이하', 'single_select', null, 'data', now(), 'aivelabs', now(), 'aivelabs', 'N', 2, 2),
            (133, 'r_score_1y', '133', 'd_cond', '조건 선택', 'ls', '이하', 'single_select', null, 'data', now(), 'aivelabs', now(), 'aivelabs', 'N', 2, 2),
            (133, 'r_score_1y', '133', 'd_cond', '조건 선택', 'gt', '이상', 'single_select', null, 'data', now(), 'aivelabs', now(), 'aivelabs', 'N', 1, 2),
            (134, 'f_score_1y', '134', 'd_cond', '조건 선택', 'ls', '이하', 'single_select', null, 'data', now(), 'aivelabs', now(), 'aivelabs', 'N', 2, 2),
            (134, 'f_score_1y', '134', 'd_cond', '조건 선택', 'gt', '이상', 'single_select', null, 'data', now(), 'aivelabs', now(), 'aivelabs', 'N', 1, 2),
            (135, 'm_score_1y', '135', 'd_cond', '조건 선택', 'gt', '이상', 'single_select', null, 'data', now(), 'aivelabs', now(), 'aivelabs', 'N', 1, 2),
            (135, 'm_score_1y', '135', 'd_cond', '조건 선택', 'ls', '이하', 'single_select', null, 'data', now(), 'aivelabs', now(), 'aivelabs', 'N', 2, 2),
            (136, 'rfm_score_1y', '136', 'd_cond', '조건 선택', 'ls', '이하', 'single_select', null, 'data', now(), 'aivelabs', now(), 'aivelabs', 'N', 2, 2),
            (136, 'rfm_score_1y', '136', 'd_cond', '조건 선택', 'gt', '이상', 'single_select', null, 'data', now(), 'aivelabs', now(), 'aivelabs', 'N', 1, 2),
            (137, 'sale_qty', '138', 'd_period', '최근경과일 선택', 'current_year', '2024년', 'single_select', null, 'data', now(), 'aivelabs', now(), 'aivelabs', 'N', 4, 1),
            (137, 'sale_qty', '138', 'd_period', '최근경과일 선택', '1y', '최근 1년', 'single_select', null, 'data', now(), 'aivelabs', now(), 'aivelabs', 'N', 6, 1),
            (137, 'sale_qty', '138', 'd_period', '최근경과일 선택', '6m', '최근 6개월', 'single_select', null, 'data', now(), 'aivelabs', now(), 'aivelabs', 'N', 7, 1),
            (137, 'sale_qty', '138', 'd_period', '최근경과일 선택', '3m', '최근 3개월', 'single_select', null, 'data', now(), 'aivelabs', now(), 'aivelabs', 'N', 8, 1),
            (137, 'sale_qty', '138', 'd_period', '최근경과일 선택', 'before_3_years', '2021년', 'single_select', null, 'data', now(), 'aivelabs', now(), 'aivelabs', 'N', 1, 1),
            (137, 'sale_qty', '138', 'd_cond', '조건 선택', 'gt', '이상', 'single_select', null, 'data', now(), 'aivelabs', now(), 'aivelabs', 'N', 1, 2),
            (137, 'sale_qty', '138', 'd_cond', '조건 선택', 'ls', '이하', 'single_select', null, 'data', now(), 'aivelabs', now(), 'aivelabs', 'N', 2, 2),
            (137, 'sale_qty', '138', 'd_cond', '조건 선택', 'eq', '같음', 'single_select', null, 'data', now(), 'aivelabs', now(), 'aivelabs', 'N', 3, 2),
            (137, 'sale_qty', '138', 'd_period', '최근경과일 선택', 'before_1_year', '2023년', 'single_select', null, 'data', now(), 'aivelabs', now(), 'aivelabs', 'N', 3, 1),
            (137, 'sale_qty', '138', 'd_period', '최근경과일 선택', 'before_2_years', '2022년', 'single_select', null, 'data', now(), 'aivelabs', now(), 'aivelabs', 'N', 2, 1),
            (137, 'sale_qty', '138', 'd_period', '최근경과일 선택', '1m', '최근 1개월', 'single_select', null, 'data', now(), 'aivelabs', now(), 'aivelabs', 'N', 9, 1),
            (137, 'sale_qty', '138', 'd_period', '최근경과일 선택', '2y', '최근 2년', 'single_select', null, 'data', now(), 'aivelabs', now(), 'aivelabs', 'N', 5, 1),
            (138, 'sale_amt', '138', 'd_period', '최근경과일 선택', 'current_year', '2024년', 'single_select', null, 'data', now(), 'aivelabs', now(), 'aivelabs', 'N', 4, 1),
            (138, 'sale_amt', '138', 'd_period', '최근경과일 선택', '2y', '최근 2년', 'single_select', null, 'data', now(), 'aivelabs', now(), 'aivelabs', 'N', 5, 1),
            (138, 'sale_amt', '138', 'd_period', '최근경과일 선택', '1y', '최근 1년', 'single_select', null, 'data', now(), 'aivelabs', now(), 'aivelabs', 'N', 6, 1),
            (138, 'sale_amt', '138', 'd_period', '최근경과일 선택', '6m', '최근 6개월', 'single_select', null, 'data', now(), 'aivelabs', now(), 'aivelabs', 'N', 7, 1),
            (138, 'sale_amt', '138', 'd_period', '최근경과일 선택', '3m', '최근 3개월', 'single_select', null, 'data', now(), 'aivelabs', now(), 'aivelabs', 'N', 8, 1),
            (138, 'sale_amt', '138', 'd_cond', '조건 선택', 'gt', '이상', 'single_select', null, 'data', now(), 'aivelabs', now(), 'aivelabs', 'N', 1, 2),
            (138, 'sale_amt', '138', 'd_cond', '조건 선택', 'ls', '이하', 'single_select', null, 'data', now(), 'aivelabs', now(), 'aivelabs', 'N', 2, 2),
            (138, 'sale_amt', '138', 'd_cond', '조건 선택', 'eq', '같음', 'single_select', null, 'data', now(), 'aivelabs', now(), 'aivelabs', 'N', 3, 2),
            (138, 'sale_amt', '138', 'd_period', '최근경과일 선택', '1m', '최근 1개월', 'single_select', null, 'data', now(), 'aivelabs', now(), 'aivelabs', 'N', 9, 1),
            (138, 'sale_amt', '138', 'd_period', '최근경과일 선택', 'before_3_years', '2021년', 'single_select', null, 'data', now(), 'aivelabs', now(), 'aivelabs', 'N', 1, 1),
            (138, 'sale_amt', '138', 'd_period', '최근경과일 선택', 'before_2_years', '2022년', 'single_select', null, 'data', now(), 'aivelabs', now(), 'aivelabs', 'N', 2, 1),
            (138, 'sale_amt', '138', 'd_period', '최근경과일 선택', 'before_1_year', '2023년', 'single_select', null, 'data', now(), 'aivelabs', now(), 'aivelabs', 'N', 3, 1),
            (141, 'coupon_expired', '141', 'd_yn', '쿠폰만료 7일 이내', 'Y', 'Y', 'single_select', null, 'data', now(), 'aivelabs', now(), 'aivelabs', 'N', 1, 1),
            (141, 'coupon_expired', '141', 'd_yn', '쿠폰만료 7일 이내', 'N', 'N', 'single_select', null, 'data', now(), 'aivelabs', now(), 'aivelabs', 'N', 2, 1),
            (142, 'is_cart', '142', 'd_yn', '업데이트 1일 이내', 'Y', 'Y', 'single_select', null, 'data', now(), 'aivelabs', now(), 'aivelabs', 'N', 1, 1),
            (142, 'is_cart', '142', 'd_yn', '업데이트 1일 이내', 'N', 'N', 'single_select', null, 'data', now(), 'aivelabs', now(), 'aivelabs', 'N', 2, 1),
            (144, 'is_wishlist', '144', 'd_yn', '위시리스트 업데이트 1일 이내', 'N', 'N', 'single_select', null, 'data', now(), 'aivelabs', now(), 'aivelabs', 'N', 2, 1),
            (144, 'is_wishlist', '144', 'd_yn', '위시리스트 업데이트 1일 이내', 'Y', 'Y', 'single_select', null, 'data', now(), 'aivelabs', now(), 'aivelabs', 'N', 1, 1),
            (149, 'purchase_cnt', '149', 'd_cond', '조건 선택', 'gt', '이상', 'single_select', null, 'data', now(), 'aivelabs', now(), 'aivelabs', 'N', 1, 1),
            (149, 'purchase_cnt', '149', 'd_cond', '조건 선택', 'ls', '이하', 'single_select', null, 'data', now(), 'aivelabs', now(), 'aivelabs', 'N', 2, 1),
            (150, 'first_purchase', '150', 'd_yn', '어제 첫 구매가 발생한 고객', 'N', 'N', 'single_select', null, 'data', now(), 'aivelabs', now(), 'aivelabs', 'N', 2, 1),
            (150, 'first_purchase', '150', 'd_yn', '어제 첫 구매가 발생한 고객', 'Y', 'Y', 'single_select', null, 'data', now(), 'aivelabs', now(), 'aivelabs', 'N', 1, 1),
            (152, 'visit_count', '152', 'd_date', '날짜선택', '날짜선택', '날짜선택', 'date_range_picker', null, 'data', now(), 'aivelabs', now(), 'aivelabs', 'N', 1, 1),
            (152, 'visit_count', '152', 'd_cond', '조건 선택', 'gt', '이상', 'single_select', null, 'data', now(), 'aivelabs', now(), 'aivelabs', 'N', 1, 2),
            (152, 'visit_count', '152', 'd_cond', '조건 선택', 'ls', '이하', 'single_select', null, 'data', now(), 'aivelabs', now(), 'aivelabs', 'N', 2, 2),
            (152, 'visit_count', '152', 'd_cond', '조건 선택', 'eq', '같음', 'single_select', null, 'data', now(), 'aivelabs', now(), 'aivelabs', 'N', 3, 2),
            (153, 'visit_count_category', '153', 'd_visit_period', '최근경과일 선택', '90d', '최근 90일', 'single_select', null, 'data', now(), 'aivelabs', now(), 'aivelabs', 'N', 5, 1),
            (153, 'visit_count_category', '153', 'd_visit_period', '최근경과일 선택', '60d', '최근 60일', 'single_select', null, 'data', now(), 'aivelabs', now(), 'aivelabs', 'N', 4, 1),
            (153, 'visit_count_category', '153', 'd_visit_period', '최근경과일 선택', '30d', '최근 30일', 'single_select', null, 'data', now(), 'aivelabs', now(), 'aivelabs', 'N', 3, 1),
            (153, 'visit_count_category', '153', 'd_visit_period', '최근경과일 선택', '14d', '최근 14일', 'single_select', null, 'data', now(), 'aivelabs', now(), 'aivelabs', 'N', 2, 1),
            (153, 'visit_count_category', '153', 'd_visit_period', '최근경과일 선택', '7d', '최근 7일', 'single_select', null, 'data', now(), 'aivelabs', now(), 'aivelabs', 'N', 1, 1),
            (153, 'visit_count_category', '153', 'd_cond', '조건 선택', 'gt', '이상', 'single_select', null, 'data', now(), 'aivelabs', now(), 'aivelabs', 'N', 1, 2),
            (153, 'visit_count_category', '153', 'd_cond', '조건 선택', 'ls', '이하', 'single_select', null, 'data', now(), 'aivelabs', now(), 'aivelabs', 'N', 2, 2),
            (153, 'visit_count_category', '153', 'd_cond', '조건 선택', 'eq', '같음', 'single_select', null, 'data', now(), 'aivelabs', now(), 'aivelabs', 'N', 3, 2),
            (156, 'visit_option_product_name', '156', 'd_visit_option_product_name', '상품 선택', '선택 옵션이 존재하지 않습니다', '선택 옵션이 존재하지 않습니다', 'multi_select', null, 'data', now(), 'aivelabs', now(), 'aivelabs', 'Y', 1, 1),
            (157, 'visit_option_full_category_name_1', '157', 'd_visit_option_category_big', '카테고리(대) 선택', '선택 옵션이 존재하지 않습니다', '선택 옵션이 존재하지 않습니다', 'multi_select', null, 'data', now(), 'aivelabs', now(), 'aivelabs', 'Y', 1, 1),
            (158, 'visit_option_full_category_name_2', '158', 'd_visit_option_category_mdl', '카테고리(중) 선택', '선택 옵션이 존재하지 않습니다', '선택 옵션이 존재하지 않습니다', 'multi_select', null, 'data', now(), 'aivelabs', now(), 'aivelabs', 'Y', 1, 1),
            (159, 'visit_option_full_category_name_3', '159', 'd_visit_option_category_sml', '카테고리(소) 선택', '선택 옵션이 존재하지 않습니다', '선택 옵션이 존재하지 않습니다', 'multi_select', null, 'data', now(), 'aivelabs', now(), 'aivelabs', 'Y', 1, 1),
            (160, 'visit_product_name', '160', 'd_visit_product_name', '상품 선택', '상품테스트4', '상품테스트4', 'multi_select', null, 'data', now(), 'aivelabs', now(), 'aivelabs', 'N', 1, 1),
            (161, 'visit_full_category_name_1', '161', 'd_visit_full_category_name_1', '카테고리(대) 선택', '선택 옵션이 존재하지 않습니다', '선택 옵션이 존재하지 않습니다', 'multi_select', null, 'data', now(), 'aivelabs', now(), 'aivelabs', 'N', 1, 1),
            (162, 'visit_full_category_name_2', '162', 'd_visit_full_category_name_2', '카테고리(중) 선택', '선택 옵션이 존재하지 않습니다', '선택 옵션이 존재하지 않습니다', 'multi_select', null, 'data', now(), 'aivelabs', now(), 'aivelabs', 'N', 1, 1),
            (163, 'visit_full_category_name_3', '163', 'd_visit_full_category_name_3', '카테고리(소) 선택', '선택 옵션이 존재하지 않습니다', '선택 옵션이 존재하지 않습니다', 'multi_select', null, 'data', now(), 'aivelabs', now(), 'aivelabs', 'N', 1, 1),
            (164, 'visit_page_title', '164', 'd_visit_page_title', '방문 페이지 선택', '페이지1', '페이지1', 'multi_select', null, 'data', now(), 'aivelabs', now(), 'aivelabs', 'N', 1, 1),
            (165, 'it_gb_nm', '165', 'd_it_gb', '카테고리 선택', '(중분류) Jackets', '(중분류) Jackets', 'multi_select', null, 'data', now(), 'aivelabs', now(), 'aivelabs', 'Y', 1, 1),
            (166, 'item_nm', '166', 'd_item_nm', '세부 카테고리 선택', '(대분류) Dresses', '(대분류) Dresses', 'multi_select', null, 'data', now(), 'aivelabs', now(), 'aivelabs', 'Y', 1, 1),
            (167, 'option_value_1', '167', 'd_option_value_1', '세부옵션 선택1', '선택 옵션이 존재하지 않습니다', '선택 옵션이 존재하지 않습니다', 'multi_select', null, 'data', now(), 'aivelabs', now(), 'aivelabs', 'Y', 1, 1),
            (168, 'option_value_2', '168', 'd_option_value_2', '세부옵션 선택2', '선택 옵션이 존재하지 않습니다', '선택 옵션이 존재하지 않습니다', 'multi_select', null, 'data', now(), 'aivelabs', now(), 'aivelabs', 'Y', 1, 1),
            (169, 'kakao_friends_yn', '169', 'd_yn', '카카오플러스 친구 여부', 'Y', 'Y', 'single_select', null, 'data', now(), 'aivelabs', now(), 'aivelabs', 'N', 1, 1),
            (169, 'kakao_friends_yn', '169', 'd_yn', '카카오플러스 친구 여부', 'N', 'N', 'single_select', null, 'data', now(), 'aivelabs', now(), 'aivelabs', 'N', 2, 1),
            (170, 'product_name', '170', 'd_product_name', '상품 선택', '상품테스트4', '상품테스트4', 'multi_select', null, 'data', now(), 'aivelabs', now(), 'aivelabs', 'Y', 1, 1),
            (171, 'is_first_best_items', '171', 'd_yn', '첫 구매 Best 상품 추천 여부', 'Y', 'Y', 'single_select', null, 'data', now(), 'aivelabs', now(), 'aivelabs', 'N', 1, 1),
            (171, 'is_first_best_items', '171', 'd_yn', '첫 구매 Best 상품 추천 여부', 'N', 'N', 'single_select', null, 'data', now(), 'aivelabs', now(), 'aivelabs', 'N', 2, 1),
            (172, 'is_steady_items', '172', 'd_yn', '스테디셀러 상품 추천 여부', 'Y', 'Y', 'single_select', null, 'data', now(), 'aivelabs', now(), 'aivelabs', 'N', 1, 1),
            (172, 'is_steady_items', '172', 'd_yn', '스테디셀러 상품 추천 여부', 'N', 'N', 'single_select', null, 'data', now(), 'aivelabs', now(), 'aivelabs', 'N', 2, 1),
            (173, 'is_best_new_items', '173', 'd_yn', '신상품 추천 여부', 'Y', 'Y', 'single_select', null, 'data', now(), 'aivelabs', now(), 'aivelabs', 'N', 1, 1),
            (173, 'is_best_new_items', '173', 'd_yn', '신상품 추천 여부', 'N', 'N', 'single_select', null, 'data', now(), 'aivelabs', now(), 'aivelabs', 'N', 2, 1),
            (174, 'is_best_category_items', '174', 'd_yn', '선호 카테고리 Best 상품 추천 여부', 'Y', 'Y', 'single_select', null, 'data', now(), 'aivelabs', now(), 'aivelabs', 'N', 1, 1),
            (174, 'is_best_category_items', '174', 'd_yn', '선호 카테고리 Best 상품 추천 여부', 'N', 'N', 'single_select', null, 'data', now(), 'aivelabs', now(), 'aivelabs', 'N', 2, 1),
            (175, 'is_best_promo_items', '175', 'd_yn', '최대 할인 상품 추천 여부', 'N', 'N', 'single_select', null, 'data', now(), 'aivelabs', now(), 'aivelabs', 'N', 2, 1),
            (175, 'is_best_promo_items', '175', 'd_yn', '최대 할인 상품 추천 여부', 'Y', 'Y', 'single_select', null, 'data', now(), 'aivelabs', now(), 'aivelabs', 'N', 1, 1),
            (176, 'is_best_cross_items', '176', 'd_yn', 'Next구매 확률 높은 상품 추천 여부', 'N', 'N', 'single_select', null, 'data', now(), 'aivelabs', now(), 'aivelabs', 'N', 2, 1),
            (176, 'is_best_cross_items', '176', 'd_yn', 'Next구매 확률 높은 상품 추천 여부', 'Y', 'Y', 'single_select', null, 'data', now(), 'aivelabs', now(), 'aivelabs', 'N', 1, 1);
    """
    connection.execute(text(variable_options_insert_query))

    connection = op.get_bind()
    variable_table_insert_query = """
        INSERT INTO aivelabs_sv.variable_table_info
            (variable_type, variable_id, target_table)
        VALUES
            ('target', 'cus_cd', 'CustomerInfoStatusEntity'),
            ('target', 'last_purchase_months_ago', 'CustomerInfoStatusEntity'),
            ('target', 'used_points', 'CustomerInfoStatusEntity'),
            ('target', 'total_points', 'CustomerInfoStatusEntity'),
            ('target', 'sale_amt_year', 'CustomerInfoStatusEntity'),
            ('target', 'cv_model', 'CustomerInfoStatusEntity'),
            ('target', 'r_score_3m', 'CustomerInfoStatusEntity'),
            ('target', 'f_score_3m', 'CustomerInfoStatusEntity'),
            ('target', 'm_score_3m', 'CustomerInfoStatusEntity'),
            ('target', 'rfm_score_3m', 'CustomerInfoStatusEntity'),
            ('target', 'r_score_6m', 'CustomerInfoStatusEntity'),
            ('target', 'f_score_6m', 'CustomerInfoStatusEntity'),
            ('target', 'm_score_6m', 'CustomerInfoStatusEntity'),
            ('target', 'rfm_score_6m', 'CustomerInfoStatusEntity'),
            ('target', 'r_score_1y', 'CustomerInfoStatusEntity'),
            ('target', 'f_score_1y', 'CustomerInfoStatusEntity'),
            ('target', 'm_score_1y', 'CustomerInfoStatusEntity'),
            ('target', 'rfm_score_1y', 'CustomerInfoStatusEntity'),
            ('target', 'last_login_date', 'CustomerInfoStatusEntity'),
            ('target', 'sms', 'CustomerInfoStatusEntity'),
            ('target', 'last_purchase_date', 'CustomerInfoStatusEntity'),
            ('target', 'first_purchase_date', 'CustomerInfoStatusEntity'),
            ('target', 'created_date', 'CustomerInfoStatusEntity'),
            ('target', 'news_mail', 'CustomerInfoStatusEntity'),
            ('target', 'available_points', 'CustomerInfoStatusEntity'),
            ('target', 'coupon_expired', 'CustomerInfoStatusEntity'),
            ('target', 'is_cart', 'CustomerInfoStatusEntity'),
            ('target', 'cart_product_no', 'CustomerInfoStatusEntity'),
            ('target', 'is_wishlist', 'CustomerInfoStatusEntity'),
            ('target', 'wishlist_product_no', 'CustomerInfoStatusEntity'),
            ('target', 'purchase_cnt', 'CustomerInfoStatusEntity'),
            ('target', 'first_purchase', 'CustomerInfoStatusEntity'),
            ('target', 'is_first_best_items', 'CustomerInfoStatusEntity'),
            ('target', 'is_steady_items', 'CustomerInfoStatusEntity'),
            ('target', 'is_best_new_items', 'CustomerInfoStatusEntity'),
            ('target', 'is_best_category_items', 'CustomerInfoStatusEntity'),
            ('target', 'is_best_promo_items', 'CustomerInfoStatusEntity'),
            ('target', 'is_best_cross_items', 'CustomerInfoStatusEntity'),
            ('target', 'kakao_friends_yn', 'CustomerInfoStatusEntity'),
            ('target', 'sale_amt', 'CustomerProductPurchaseSummaryEntity'),
            ('target', 'sale_qty', 'CustomerProductPurchaseSummaryEntity'),
            ('target', 'milege_usage', 'CustomerProductPurchaseSummaryEntity'),
            ('target', 'it_gb_nm', 'CustomerProductPurchaseSummaryEntity'),
            ('target', 'item_nm', 'CustomerProductPurchaseSummaryEntity'),
            ('target', 'product_name', 'CustomerProductPurchaseSummaryEntity'),
            ('target', 'option_value_1', 'CustomerProductPurchaseSummaryEntity'),
            ('target', 'option_value_2', 'CustomerProductPurchaseSummaryEntity'),
            ('target', 'visit_full_category_name_3', 'GaViewMasterEntity'),
            ('target', 'visit_page_title', 'GaViewMasterEntity'),
            ('target', 'visit_product_name', 'GaViewMasterEntity'),
            ('target', 'visit_count', 'GaViewMasterEntity'),
            ('target', 'visit_full_category_name_1', 'GaViewMasterEntity'),
            ('target', 'visit_full_category_name_2', 'GaViewMasterEntity');
    """
    connection.execute(text(variable_table_insert_query))


def downgrade():
    connection = op.get_bind()
    delete_query = "DELETE FROM aivelabs_sv.audience_predefiend_variables;"
    connection.execute(text(delete_query))

    connection = op.get_bind()
    delete_query = "DELETE FROM aivelabs_sv.variable_options;"
    connection.execute(text(delete_query))

    connection = op.get_bind()
    delete_query = "DELETE FROM aivelabs_sv.variable_table_info;"
    connection.execute(text(delete_query))
