from datetime import datetime
from typing import Optional

from pydantic import BaseModel


class Product(BaseModel):
    shop_no: Optional[int]
    product_no: Optional[int]
    product_code: Optional[str]
    custom_product_code: Optional[str]
    brand_code: Optional[str]
    trend_code: Optional[str]
    product_name: Optional[str]
    eng_product_name: Optional[str]
    supply_product_name: Optional[str]
    internal_product_name: Optional[str]
    model_name: Optional[str]
    brand_name: Optional[str]
    trend_name: Optional[str]
    category_no: Optional[float]
    category_name: Optional[str]
    category_depth: Optional[str]
    full_category_name_1: Optional[str]
    full_category_name_2: Optional[str]
    full_category_name_3: Optional[str]
    full_category_name_4: Optional[str]
    full_category_no_1: Optional[str]
    full_category_no_2: Optional[str]
    full_category_no_3: Optional[str]
    full_category_no_4: Optional[str]
    is_bundle: Optional[str]
    made_date: Optional[str]
    release_date: Optional[str]
    created_date: Optional[str]
    detail_image: Optional[str]
    list_image: Optional[str]
    tiny_image: Optional[str]
    small_image: Optional[str]
    additional_image: Optional[str]
    display: Optional[str]
    selling: Optional[str]
    product_condition: Optional[str]
    sold_out: Optional[str]
    price: Optional[int]
    retail_price: Optional[int]
    additional_price: Optional[int]
    discountprice: Optional[int]
    cloth_fabric: Optional[str]
    product_material: Optional[str]
    summary_description: Optional[str]
    simple_description: Optional[str]
    product_tag: Optional[str]
    buy_limit_by_product: Optional[str]
    single_purchase_restriction: Optional[str]
    adult_certification: Optional[str]
    expiration_date_start_date: Optional[str]
    expiration_date_end_date: Optional[str]
    options: Optional[str]
    variants: Optional[str]
    exposure_limit_type: Optional[str]
    exposure_group_list: Optional[str]
    set_product_type: Optional[str]
    shipping_fee_type: Optional[str]
    main: Optional[str]
    memos: Optional[str]
    hits: Optional[int]
    seo: Optional[str]
    project_no: Optional[str]
    exchange_info: Optional[str]
    additional_information: Optional[str]
    relational_product: Optional[str]
    comment: Optional[str]
    recommend_yn: Optional[str]
    rep_nm: Optional[str]
    created_at: Optional[str]
    updated_at: Optional[str]
    etltime: Optional[datetime]

    class Config:
        from_attributes = True
