from sqlalchemy import ARRAY, Column, Integer, String

from src.core.database import Base as Base


class CustomerProductPurchaseSummaryEntity(Base):
    __tablename__ = "cus_product_purchase_summary"

    cus_product_prucahse_seq = Column(Integer, primary_key=True)
    cus_cd = Column(String, nullable=True)
    sup_gu_grp_nm = Column(String, nullable=True)
    it_gb_nm = Column(String, nullable=True)
    item_nm = Column(String, nullable=True)
    item_sb_nm = Column(String, nullable=True)
    rep_nm = Column(String, nullable=True)
    purpose1 = Column(String, nullable=True)
    oldnew_yn = Column(String, nullable=True)
    col_gb_nm = Column(String, nullable=True)
    prd_length = Column(String, nullable=True)
    prd_fit = Column(String, nullable=True)
    prd_core_mat = Column(String, nullable=True)
    prd_design = Column(String, nullable=True)
    d_line_nm = Column(String, nullable=True)
    sty_season_nm = Column(String, nullable=True)
    sty_cd = Column(String, nullable=True)
    shop_tp2_nm = Column(String, nullable=True)
    shop_tp4_nm = Column(String, nullable=True)
    shop_tp5_nm = Column(String, nullable=True)
    sale_amt_before_3_years = Column(Integer)
    sale_amt_before_2_years = Column(Integer)
    sale_amt_before_1_year = Column(Integer)
    sale_amt_current_year = Column(Integer)
    sale_amt_2y = Column(Integer)
    sale_amt_1y = Column(Integer)
    sale_amt_6m = Column(Integer)
    sale_amt_3m = Column(Integer)
    sale_amt_1m = Column(Integer)
    sale_amt_ss = Column(Integer)
    sale_amt_fw = Column(Integer)
    sale_qty_before_3_years = Column(Integer)
    sale_qty_before_2_years = Column(Integer)
    sale_qty_before_1_year = Column(Integer)
    sale_qty_current_year = Column(Integer)
    sale_qty_2y = Column(Integer)
    sale_qty_1y = Column(Integer)
    sale_qty_6m = Column(Integer)
    sale_qty_3m = Column(Integer)
    sale_qty_1m = Column(Integer)
    sale_qty_ss = Column(Integer)
    sale_qty_fw = Column(Integer)
    sale_dt_array_before_3_years = Column(ARRAY(String), nullable=True)
    sale_dt_array_before_2_years = Column(ARRAY(String), nullable=True)
    sale_dt_array_before_1_year = Column(ARRAY(String), nullable=True)
    sale_dt_array_current_year = Column(ARRAY(String), nullable=True)
    sale_dt_array_2y = Column(ARRAY(String), nullable=True)
    sale_dt_array_1y = Column(ARRAY(String), nullable=True)
    sale_dt_array_6m = Column(ARRAY(String), nullable=True)
    sale_dt_array_3m = Column(ARRAY(String), nullable=True)
    sale_dt_array_1m = Column(ARRAY(String), nullable=True)
    sale_dt_array_ss = Column(ARRAY(String), nullable=True)
    sale_dt_array_fw = Column(ARRAY(String), nullable=True)
    milege_usage_before_3_years = Column(Integer)
    milege_usage_before_2_years = Column(Integer)
    milege_usage_before_1_year = Column(Integer)
    milege_usage_current_year = Column(Integer)
    milege_usage_2y = Column(Integer)
    milege_usage_1y = Column(Integer)
    milege_usage_6m = Column(Integer)
    milege_usage_3m = Column(Integer)
    milege_usage_1m = Column(Integer)
    milege_usage_ss = Column(Integer)
    milege_usage_fw = Column(Integer)
