from sqlalchemy import Column, Float, Integer, String

from src.core.database import Base as Base


class PurchaseAnalyticsMasterStyle(Base):
    __tablename__ = "temp_purchase_analytics_master_style"

    purchase_analytics_master_style_seq = Column(Integer, primary_key=True)
    recp_no = Column(String, primary_key=True)
    cus_cd = Column(String, primary_key=True)
    age = Column(Integer)
    sex = Column(String, nullable=True)
    shop_cd = Column(String, nullable=True)
    re_shop_cd2 = Column(String, nullable=True)
    shop_tp2_nm = Column(String, nullable=True)
    shop_tp4_nm = Column(String, nullable=True)
    shop_tp5_nm = Column(String, nullable=True)
    shop_mng_gb = Column(String, nullable=True)
    shop_mng_gb_nm = Column(String, nullable=True)
    team_cd = Column(String, nullable=True)
    team_nm = Column(String, nullable=True)
    sale_dt = Column(String, nullable=True)
    yoil_nm = Column(String, nullable=True)
    sty_cd = Column(String, primary_key=True)
    sty_nm = Column(String, nullable=True)
    running_yn = Column(String, nullable=True)
    oldnew_yn = Column(String, nullable=True)
    sale_qty = Column(Integer)
    sale_amt = Column(Integer)
    cons_amt = Column(Integer)
    dc_rate = Column(Float)
    milege_usage = Column(Integer)
    event_tp = Column(String, nullable=True)
    event_no = Column(String, nullable=True)
    event_dc_amt = Column(Integer)
    base_sale_pri = Column(Integer)
    pnt_rate = Column(Integer)
    pnt_samt = Column(Integer)
    sty_season_nm = Column(String, nullable=True)
    sty_season_grop_nm = Column(String, nullable=True)
    year2 = Column(String, nullable=True)
    sty_sex = Column(String, nullable=True)
    it_gb_nm = Column(String, nullable=True)
    item_nm = Column(String, nullable=True)
    item_sb_nm = Column(String, nullable=True)
    d_line_nm = Column(String, nullable=True)
    sup_gu_grp_nm = Column(String, nullable=True)
    purpose1 = Column(String, nullable=True)
    purpose2 = Column(String, nullable=True)
    purpose3 = Column(String, nullable=True)
    rep_nm = Column(String, nullable=True)
    prd_fit = Column(String, nullable=True)
    prd_length = Column(String, nullable=True)
    col_nm = Column(String, nullable=True)
    col_gb_nm = Column(String, nullable=True)
    prd_core_mat = Column(String, nullable=True)
    size_cd = Column(String, nullable=True)
    prd_design = Column(String, nullable=True)
    prd_target = Column(String, nullable=True)
    sty_gb = Column(String, nullable=True)
