server:
  http_listen_port: 9080
  grpc_listen_port: 0

clients:
  - url: ${LOKI_URL}

positions:
  filename: /etc/promtail/positions.yaml

scrape_configs:
  - job_name: system_logs
    static_configs:
      - targets:
          - localhost
        labels:
          job: aace-app-log
          __path__: /var/log/app.log*
    pipeline_stages:
      - multiline:
          firstline: '^\[\d{4}-\d{2}-\d{2} \d{2}:\d{2}:\d{2},\d{3}\]\[\w+\]\[.*\] .*'
          max_wait_time: 3s
